spring:
  application:
    name: mallapi

  datasource:
    url: jdbc:mysql://localhost:3306/malldb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: malldbuser
    password: malldbuser
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/malldb

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    com.zaxxer: info
    org.springframework.security.web: trace
#    org.springframework.data.mongodb.core: DEBUG
#    org.mongodb.driver: DEBUG

org:
  zerock:
    upload:
      todo:
        path: upload/todo_files
      product:
        path: product_files
